config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'

  resources :lists
  root 'lists#index' 
  get 'home/remove_deleted'
  get 'home/remove_all'
  

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def remove_deleted
        @remove_deleted = List.where(:completed => true).destroy_all
        redirect_to lists_url, notice: 'All marked items were removed.'
    end 
    
    def remove_all
        @remove_all= List.all.destroy_all
        redirect_to lists_url, notice: 'All items were removed.'
    end 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    # 
    @list = List.new
    # list calls and gets everything from the database
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!--          Everything here shows up on every page          -->
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'lists/navbar' %>

<div class="container">
  <%= render 'flash' %>  
  <%= yield %>
</div>

</body>
</html>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class ="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %> 
    </div>
<% end %> 

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
  <div class="form-group">
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group form-check">
    <%= f.check_box :completed , class: "form-check-input" %>
    <%= f.label :completed, class: 'form-check-label'%>
  </div>
  <div class="actions">
   <%= f.submit  "Update!", class: "btn btn-warning" %>
  </div>
  </center> 
<% end %>

app/views/lists/_form_index.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <%= f.text_field :description, class: "form-control mr-sm-2" %>
    <%= f.submit "Add item", class: "btn btn-outline-success my-2 my-sm-0"  %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "To Do List", root_path, class: 'navbar-brand' %>
 
  <%= social_share_button_tag("To Do List") %>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <%= render 'form_index' %>

  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Edit Task</h1>
</br>
<!--render is a 'partial' that allows you to pull something from another page onto this page-->
<!--A Partial starts with a '_'-->

<div class="card" style="width: 18rem;">
  <div class="card-body">
     <%= render 'form' %>  
  </div>
</div>
          
<br/> <br/>
<% link_to 'Show', @list %> 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<table class="table table-bordered">
  <tbody>
    <% @lists.each do |list| %>
    
    <% if list.completed %>
      <tr class="bg-warning">

        <td class="strike_thru"><p class='text-light' <%= link_to list.description, edit_list_path(list) %><% list.description %></td></p>
        <td>
            
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
            <%= f.submit  "Undo", class: 'btn btn-outline-secondary btn-sm' %>
            <% end %>
     
        </td>
        <td>
          <% link_to 'Show', list %>                      
          <%link_to 'Edit', edit_list_path(list) %>
          <center> <%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></center>
        </td>
        
      </tr>
      <% else %>
        <tr>
        <td> <%= link_to list.description, edit_list_path(list) %><% list.description %></td>
        <td>
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
            <%= f.submit  "Done", class: 'btn btn-outline-secondary  btn-sm' %>
            <% end %>
        </td>
        <td>
 <!-- '=' means printed to the page -->
            <% link_to 'Show', list %>
            <% link_to 'Edit', edit_list_path(list) %>
            <center> <%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></center>
          </td>
        </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br/>

<% link_to 'Add item', new_list_path, class: 'btn btn-success' %>


<br/>
<br/>

<%= link_to 'Delete Marked Items', home_remove_deleted_path, class: 'btn btn-warning', data: { confirm: 'Are you sure?' }%>

<%= link_to 'Delete All', home_remove_all_path, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }%>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>To Do Item:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>